version: '3.8'
services:
  backend:
    build:
      context: ./backend-nest
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - database
    networks:
      - rexlan-network
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
    command: serve -d build -p 3000
    networks:
      - rexlan-network

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      - rexlan-network

  database:
    image: postgres:13
    ports:
      - '5432:5432'
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=postgres
    networks:
      - rexlan-network

networks:
  rexlan-network:
    driver: bridge
