server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost/rexlan
    username: postgres
    password: example
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
